# Site settings
author: Ryan McFadden
title: Why I chose Software Engineering
header-img: img/home-bg.png
email: ryanmcfadden123@gmail.com
copyright_name: Ryan McFadden
description: > # this means to ignore newlines until "baseurl:"
  But why?
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Ryan-McFadden

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
